hello_world.simple_message.*:
  type: config_entity
  label: 'Simple message config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    message:
      type: text
      label: 'Message'
    uuid:
      type: string
