hello_world.contact_person_type.*:
  type: config_entity
  label: 'Contact person type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
