hello_world.settings:
  type: config_object
  label: 'My module settings'
  mapping:
    submit_button_label:
      type: label
      label: 'Label for submit button'
    name_field_settings:
      type: mapping
      label: 'Settings for name field'
      mapping:
        field_label:
          type: label
          label: 'Label for name field'
        field_size:
          type: integer
          label: 'Size of name field'